
# Reference: https://supabase.com/docs/guides/functions/local-development

project_id = "fvxfmlhvxmpmbtouarcp"

[api]
port = 54321
schemes = ["http", "https"]
host = "127.0.0.1"

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "https://project.lovable.app"
additional_redirect_urls = ["https://project.lovable.app"]
auto_confirm_new_users = true

[[functions]]
name = "process-notes"
verify_jwt = false

[[functions]]
name = "process-task-batch"
verify_jwt = false
