
# A string used as a project reference
project_id = "fvxfmlhvxmpmbtouarcp"

[functions.process-notes]
verify_jwt = false

[functions.process-task-batch]
verify_jwt = false

[functions.process-task-enhancements]
verify_jwt = false

[functions.enhance-tasks]
verify_jwt = false
