// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvxfmlhvxmpmbtouarcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2eGZtbGh2eG1wbWJ0b3VhcmNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MjE0MzQsImV4cCI6MjA1NzI5NzQzNH0.r0h6kc5obgxrzBldoCFodRoo9pbY8tghWgnjtQ2BR9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);